### ISSUE TITLE
Create Tablet - Mobile menu With react-burger-menu

### ISSUE THREAD

**Issue by CharlyJazz** [MeteoriteNetwork/PDK#20]
Hide the list on the left with the component <Hidden> of react-grid-system and use this library to create an off-canvas menu that works just like the list, show the menu with the <Visible> component of react-grid- system

https://github.com/negomi/react-burger-menu

** Styles helpers

``` css
/* Position and sizing of burger button */
.bm-burger-button {
  position: fixed;
  width: 36px;
  height: 30px;
  right: 20px;
  top: 33px;
}

/* Color/shape of burger icon bars */
.bm-burger-bars {
  background-color: rgb(119, 151, 238);
}

/* Position and sizing of clickable cross button */
.bm-cross-button {
  right: 20px !important
}
 
/* Color/shape of close button cross */
.bm-cross {
  background-color: #bdc3c7;
}

/* General sidebar styles */
.bm-menu {
  background-color: #2E354D;
  padding: 2.5em 1.5em 0;
  font-size: 1.15em;
}

/* Morph shape necessary with bubble or elastic */
.bm-morph-shape {
  fill: #373a47;
}

/* Wrapper for item list */
.bm-item-list {
  color: #b8b7ad;
  padding: 0.8em;
}

/* Styling of overlay */
.bm-overlay {
  background-color: rgba(0, 0, 0, 0.3);
}

/* Component styles */

.FixedNavBar-item {
  font-size: 2rem;
  margin-bottom: 20px;
  color: #6386E3;
  text-decoration: none
}

.FixedNavBar-item > span:nth-child(1) {
  vertical-align: middle;
}

.FixedNavBar-item > span:nth-child(2) {
  margin: 20px;
}

.FixedNavBar-item.--active {
  color: #E9C967;
}

```

Component: 
``` javascript
import React, { Component } from 'react'
import { NavLink } from 'react-router-dom'
import { stack as Menu } from 'react-burger-menu'
import MaterialIcon from 'react-google-material-icons'
import './styles.css'

class FixedNavBar extends Component {
  render() {
    return (
      <Menu
      left 
      width={'100%'} 
      customCrossIcon={ <MaterialIcon icon="close" size={36}/> }
      isOpen={false}
      >
        <NavLink
        className="FixedNavBar-item" 
        activeClassName="--active"
        exact
        to="/">
          <span>
            <MaterialIcon icon="security" size={36}/>
          </span>
          <span>
            Portfolio
          </span>
        </NavLink>

        <NavLink
        className="FixedNavBar-item" 
        activeClassName="--active"
        to="/markets">
          <span>
            <MaterialIcon icon="domain" size={36}/>
          </span>
          <span>
            Markets
          </span>
        </NavLink>

        <NavLink
        className="FixedNavBar-item" 
        activeClassName="--active"
        to="/forum">
          <span>
            <MaterialIcon icon="comment" size={36}/>
          </span>
          <span>
            Forum
          </span>
        </NavLink>

        <NavLink
        className="FixedNavBar-item" 
        activeClassName="--active"
        to="/account">
          <span>
            <MaterialIcon icon="settings" size={36}/>
          </span>
          <span>
            Account
          </span>
        </NavLink>
        
      </Menu>
    )
  }
}
 
export default FixedNavBar
```

Example of use of the component:

``` javascript
<main className="Layout-wrapper">
          <Visible md sm xs>
            <FixedNavBar/>
          </Visible>
          <div className="Layout-content-wrapper">
            <WrappedComponent {...this.props}/>
          </div>
          <Hidden md sm xs>
            <PanelMultiCharts />
          </Hidden>
        </main>
```
